[build]
  command = "yarn build"
  functions = "netlify-lambda"
  publish = "build"

[dev]
  command = "yarn start" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 9000 # port for functions server
  targetPort = 3000 # Port of target app server
  publish = "build" # If you use a _redirect file, provide the path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200